spring:
  config:
    import:
      - optional:classpath:secret-dev-local.yml
      - optional:file:./zero-admin/src/main/resources/secret-dev-local.yml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${SNAIL_JOB_DB_URL:jdbc:postgresql://${SECRET.DB.HOST:localhost}:${SECRET.DB.PORT:5432}/zero_admin}
    username: ${SNAIL_JOB_DB_USERNAME:${SECRET.DB.USERNAME:root}}
    password: ${SNAIL_JOB_DB_PASSWORD:${SECRET.DB.PASSWORD:}}
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 30000

snail-job:
  server-host: ${SNAIL_JOB_SERVER_HOST:}
  server-port: ${SNAIL_JOB_SERVER_PORT:17888}
  merge-log-days: 1
  merge-log-num: 500
  retry-pull-page-size: 100
  log-storage: 7
  bucket-total: 128
  summary-day: 7
  load-balance-cycle-time: 10
  retry-max-pull-parallel: 2

monitor:
  credentials:
    username: ${MONITOR_USERNAME:admin}
    password: ${MONITOR_PASSWORD:admin123}

spring.boot.admin.client:
  enabled: ${MONITOR_CLIENT_ENABLED:true}
  url: ${MONITOR_SERVER_URL:http://192.168.1.237:9090/admin}
  instance:
    service-host-type: ip
    metadata:
      username: ${MONITOR_USERNAME:${monitor.credentials.username}}
      userpassword: ${MONITOR_PASSWORD:${monitor.credentials.password}}
  username: ${MONITOR_USERNAME:${monitor.credentials.username}}
  password: ${MONITOR_PASSWORD:${monitor.credentials.password}}
