<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.zero.admin</groupId>
        <artifactId>zero-admin</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>zero-apps</artifactId>
    <name>zero-apps</name>
    <description>面向终端用户的可独立部署应用</description>
    <packaging>pom</packaging>

    <modules>
        <module>zero-consumer-web</module>
    </modules>
</project>
