# 项目相关配置
zeroAdmin:
  # 名称
  name: Zero-Admin
  # 版本
  version: ${revision}
  # 版权年份
  copyrightYear: 2025

captcha:
  enable: true     # 页面 <参数设置> 可开启关闭 验证码校验
  type: MATH        # 验证码类型 math 数组计算 char 字符验证
  category: CIRCLE  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  numberLength: 1   # 数字验证码位数
  charLength: 4     # 字符验证码长度

# 开发环境配置
server:
  port: 8080          # 服务器的HTTP端口，默认为8080
  servlet:
    context-path: /   # 应用的访问路径
  undertow:           # undertow 配置
    max-http-post-size: -1    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 512          # 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true      # 是否分配的直接内存
    threads:
      io: 8                   # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      worker: 256             # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载

# 日志配置
logging:
  level:
    com.zero.admin: @logging.level@
    org.springframework: warn
    org.mybatis.spring.mapper: error
    org.apache.fury: warn
  config: classpath:logback-plus.xml

# 用户配置
user:
  password:
    maxRetryCount: 5  # 密码最大错误次数
    lockTime: 10      # 密码锁定时间（默认10分钟）

# Spring配置
spring:
  application:
    name: ${zeroAdmin.name}
  threads:
    virtual: # 开启虚拟线程 仅jdk21可用
      enabled: false

  messages: # 资源信息
    basename: i18n/messages # 国际化资源文件路径
  profiles:
    active: @profiles.active@

  servlet: # 文件上传
    multipart:
      max-file-size: 10MB # 单个文件大小
      max-request-size: 20MB # 设置总上传的文件大小
  mvc:
    static-path-pattern: /static/**  # 设置静态资源路径 防止所有请求都去查静态资源
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式化
    serialization:
      indent_output: false # 格式化输出
      fail_on_empty_beans: false # 忽略无法转换的对象
    deserialization:
      fail_on_unknown_properties: false # 允许对象忽略json中不存在的属性

# Sa-Token配置
sa-token:
  token-name: Authorization  # token名称 (同时也是cookie名称)
  is-concurrent: true # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-share: false # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk  # jwt秘钥

# security配置
security:
  # 排除路径
  excludes:
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /favicon.ico
    - /error
    - /*/api-docs
    - /*/api-docs/**

# 多租户配置
tenant:
  enable: false # 是否开启
  excludes:  # 排除表
    - sys_menu
    - sys_tenant
    - sys_tenant_package
    - sys_role_dept
    - sys_role_menu
    - sys_user_post
    - sys_user_role
    - sys_client
    - sys_oss_config

# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  enableLogicDelete: true # 自定义配置 是否全局开启逻辑删除 关闭后 所有逻辑删除功能将失效
  mapperPackage: com.zero.admin.**.mapper # 自定义配置 多包名使用 例如 com.zero.admin.**.mapper,org.xxx.**.mapper
  mapper-locations: classpath*:mapper/**/*Mapper.xml # 对应的 XML 文件位置
  typeAliasesPackage: com.zero.admin.**.domain # 实体扫描，多个package用逗号或者分号分隔
  global-config:
    dbConfig:
      idType: ASSIGN_ID # 主键类型; AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID; 如需改为自增 需要将数据库表全部设置为自增

# 数据加密
mybatis-encryptor:
  enable: false # 是否开启加密
  algorithm: BASE64 # 默认加密算法
  encode: BASE64 # 编码方式 BASE64/HEX。默认BASE64
  password: # 安全秘钥 对称算法的秘钥 如：AES，SM4

  # 公私钥 非对称算法的公私钥 如：SM2，RSA
  publicKey:
  privateKey:

# api接口加密
api-decrypt:
  enabled: true # 是否开启全局接口加密
  headerFlag: encrypt-key # AES 加密头标识
  # 响应加密公钥 非对称算法的公私钥 如：SM2，RSA 使用者请自行更换
  # 对应前端解密私钥 MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAmc3CuPiGL/LcIIm7zryCEIbl1SPzBkr75E2VMtxegyZ1lYRD+7TZGAPkvIsBcaMs6Nsy0L78n2qh+lIZMpLH8wIDAQABAkEAk82Mhz0tlv6IVCyIcw/s3f0E+WLmtPFyR9/WtV3Y5aaejUkU60JpX4m5xNR2VaqOLTZAYjW8Wy0aXr3zYIhhQQIhAMfqR9oFdYw1J9SsNc+CrhugAvKTi0+BF6VoL6psWhvbAiEAxPPNTmrkmrXwdm/pQQu3UOQmc2vCZ5tiKpW10CgJi8kCIFGkL6utxw93Ncj4exE/gPLvKcT+1Emnoox+O9kRXss5AiAMtYLJDaLEzPrAWcZeeSgSIzbL+ecokmFKSDDcRske6QIgSMkHedwND1olF8vlKsJUGK3BcdtM8w4Xq7BpSBwsloE=
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJnNwrj4hi/y3CCJu868ghCG5dUj8wZK++RNlTLcXoMmdZWEQ/u02RgD5LyLAXGjLOjbMtC+/J9qofpSGTKSx/MCAwEAAQ==
  # 请求解密私钥 非对称算法的公私钥 如：SM2，RSA 使用者请自行更换
  # 对应前端加密公钥 MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKoR8mX0rGKLqzcWmOzbfj64K8ZIgOdHnzkXSOVOZbFu/TJhZ7rFAN+eaGkl3C4buccQd/EjEsj9ir7ijT7h96MCAwEAAQ==
  privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAqhHyZfSsYourNxaY7Nt+PrgrxkiA50efORdI5U5lsW79MmFnusUA355oaSXcLhu5xxB38SMSyP2KvuKNPuH3owIDAQABAkAfoiLyL+Z4lf4Myxk6xUDgLaWGximj20CUf+5BKKnlrK+Ed8gAkM0HqoTt2UZwA5E2MzS4EI2gjfQhz5X28uqxAiEA3wNFxfrCZlSZHb0gn2zDpWowcSxQAgiCstxGUoOqlW8CIQDDOerGKH5OmCJ4Z21v+F25WaHYPxCFMvwxpcw99EcvDQIgIdhDTIqD2jfYjPTY8Jj3EDGPbH2HHuffvflECt3Ek60CIQCFRlCkHpi7hthhYhovyloRYsM+IS9h/0BzlEAuO0ktMQIgSPT3aFAgJYwKpqRYKlLDVcflZFCKY7u3UP8iWi1Qw0Y=

springdoc:
  api-docs:
    enabled: true # 是否开启接口文档
  #  swagger-ui:
  #    # 持久化认证数据
  #    persistAuthorization: true
  info:
    title: '标题：${zeroAdmin.name}多租户管理系统_接口文档'
    description: '描述：用于管理集团旗下公司的人员信息,具体包括XXX,XXX模块...'
    version: '版本号: ${zeroAdmin.version}'
    # 作者信息
    contact:
      name: Akai
      email: liaokaigogo@foxmail.com
      url:
  components:
    # 鉴权方式配置
    security-schemes:
      apiKey:
        type: APIKEY
        in: HEADER
        name: ${sa-token.token-name}
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    - group: 1.通用模块
      packages-to-scan: com.zero.admin.web
    - group: 2.系统模块
      packages-to-scan: com.zero.admin.system

# 防止XSS攻击
xss:
  enabled: true # 过滤开关
  excludeUrls: # 排除链接（多个用逗号分隔）
    - /system/notice

# 全局线程池相关配置
# 如使用JDK21请直接使用虚拟线程 不要开启此配置
thread-pool:
  enabled: false # 是否开启线程池
  queueCapacity: 128 # 队列最大长度
  keepAliveSeconds: 300 # 线程池维护线程所允许的空闲时间

--- # 分布式锁 lock4j 全局配置
lock4j:
  acquire-timeout: 3000 # 获取分布式锁超时时间，默认为 3000 毫秒
  expire: 30000 # 分布式锁的超时时间，默认为 30 秒

--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/sys-console.log

--- # 默认/推荐使用sse推送
sse:
  enabled: true
  path: /resource/sse

