<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zero.admin</groupId>
        <artifactId>zero-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>zero-system</artifactId>
    <name>zero-system</name>
    <version>${revision}</version>

    <dependencies>

        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-excel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-idempotent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-encrypt</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-sensitive</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-translation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zero.admin</groupId>
            <artifactId>zero-base-oss</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
