name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ALI_DOCKER_HOST: crpi-3i3pv7x8w1lizxgy.cn-shenzhen.personal.cr.aliyuncs.com

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install zero-base dependency
        run: mvn install:install-file -DgroupId=com.zero.admin -DartifactId=zero-base -Dversion=0.0.1 -Dpackaging=jar -Dfile=path/to/zero-base-0.0.1.jar

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Ali Docker Hub
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ env.ALI_DOCKER_HOST }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_REPO: ${{ env.ALI_DOCKER_HOST }}/akai6/zero-admin-api
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker build . --file Dockerfile --tag $DOCKER_REPO:v0.0.1
          docker push $DOCKER_REPO:v0.0.1