name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ALI_DOCKER_HOST: crpi-3i3pv7x8w1lizxgy.cn-shenzhen.personal.cr.aliyuncs.com

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Ali Docker Hub
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ env.ALI_DOCKER_HOST }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_REPO: akai6/zero-admin-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . --file Dockerfile --tag latest $DOCKER_REPO:$IMAGE_TAG
          docker push ${{ env.ALI_DOCKER_HOST }}/$DOCKER_REPO